package cn.cbdi.hunaninstrument.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cbdi.hunaninstrument.Bean.AttendanceScene;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ATTENDANCE_SCENE".
*/
public class AttendanceSceneDao extends AbstractDao<AttendanceScene, Long> {

    public static final String TABLENAME = "ATTENDANCE_SCENE";

    /**
     * Properties of entity AttendanceScene.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CardID = new Property(1, String.class, "cardID", false, "CARD_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Headphoto = new Property(3, String.class, "headphoto", false, "HEADPHOTO");
        public final static Property HeadphotoRGB = new Property(4, String.class, "headphotoRGB", false, "HEADPHOTO_RGB");
        public final static Property HeadphotoBW = new Property(5, String.class, "headphotoBW", false, "HEADPHOTO_BW");
        public final static Property FaceUserId = new Property(6, String.class, "FaceUserId", false, "FACE_USER_ID");
        public final static Property Feature = new Property(7, byte[].class, "feature", false, "FEATURE");
        public final static Property ScenePhoto = new Property(8, String.class, "ScenePhoto", false, "SCENE_PHOTO");
        public final static Property SceneHeadPhoto = new Property(9, String.class, "SceneHeadPhoto", false, "SCENE_HEAD_PHOTO");
        public final static Property FaceRecognition = new Property(10, int.class, "faceRecognition", false, "FACE_RECOGNITION");
        public final static Property AttendanceTime = new Property(11, String.class, "AttendanceTime", false, "ATTENDANCE_TIME");
        public final static Property Alive = new Property(12, Integer.class, "alive", false, "ALIVE");
    }


    public AttendanceSceneDao(DaoConfig config) {
        super(config);
    }
    
    public AttendanceSceneDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ATTENDANCE_SCENE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARD_ID\" TEXT," + // 1: cardID
                "\"NAME\" TEXT," + // 2: name
                "\"HEADPHOTO\" TEXT," + // 3: headphoto
                "\"HEADPHOTO_RGB\" TEXT," + // 4: headphotoRGB
                "\"HEADPHOTO_BW\" TEXT," + // 5: headphotoBW
                "\"FACE_USER_ID\" TEXT," + // 6: FaceUserId
                "\"FEATURE\" BLOB," + // 7: feature
                "\"SCENE_PHOTO\" TEXT," + // 8: ScenePhoto
                "\"SCENE_HEAD_PHOTO\" TEXT," + // 9: SceneHeadPhoto
                "\"FACE_RECOGNITION\" INTEGER NOT NULL ," + // 10: faceRecognition
                "\"ATTENDANCE_TIME\" TEXT," + // 11: AttendanceTime
                "\"ALIVE\" INTEGER);"); // 12: alive
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ATTENDANCE_SCENE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AttendanceScene entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardID = entity.getCardID();
        if (cardID != null) {
            stmt.bindString(2, cardID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String headphoto = entity.getHeadphoto();
        if (headphoto != null) {
            stmt.bindString(4, headphoto);
        }
 
        String headphotoRGB = entity.getHeadphotoRGB();
        if (headphotoRGB != null) {
            stmt.bindString(5, headphotoRGB);
        }
 
        String headphotoBW = entity.getHeadphotoBW();
        if (headphotoBW != null) {
            stmt.bindString(6, headphotoBW);
        }
 
        String FaceUserId = entity.getFaceUserId();
        if (FaceUserId != null) {
            stmt.bindString(7, FaceUserId);
        }
 
        byte[] feature = entity.getFeature();
        if (feature != null) {
            stmt.bindBlob(8, feature);
        }
 
        String ScenePhoto = entity.getScenePhoto();
        if (ScenePhoto != null) {
            stmt.bindString(9, ScenePhoto);
        }
 
        String SceneHeadPhoto = entity.getSceneHeadPhoto();
        if (SceneHeadPhoto != null) {
            stmt.bindString(10, SceneHeadPhoto);
        }
        stmt.bindLong(11, entity.getFaceRecognition());
 
        String AttendanceTime = entity.getAttendanceTime();
        if (AttendanceTime != null) {
            stmt.bindString(12, AttendanceTime);
        }
 
        Integer alive = entity.getAlive();
        if (alive != null) {
            stmt.bindLong(13, alive);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AttendanceScene entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardID = entity.getCardID();
        if (cardID != null) {
            stmt.bindString(2, cardID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String headphoto = entity.getHeadphoto();
        if (headphoto != null) {
            stmt.bindString(4, headphoto);
        }
 
        String headphotoRGB = entity.getHeadphotoRGB();
        if (headphotoRGB != null) {
            stmt.bindString(5, headphotoRGB);
        }
 
        String headphotoBW = entity.getHeadphotoBW();
        if (headphotoBW != null) {
            stmt.bindString(6, headphotoBW);
        }
 
        String FaceUserId = entity.getFaceUserId();
        if (FaceUserId != null) {
            stmt.bindString(7, FaceUserId);
        }
 
        byte[] feature = entity.getFeature();
        if (feature != null) {
            stmt.bindBlob(8, feature);
        }
 
        String ScenePhoto = entity.getScenePhoto();
        if (ScenePhoto != null) {
            stmt.bindString(9, ScenePhoto);
        }
 
        String SceneHeadPhoto = entity.getSceneHeadPhoto();
        if (SceneHeadPhoto != null) {
            stmt.bindString(10, SceneHeadPhoto);
        }
        stmt.bindLong(11, entity.getFaceRecognition());
 
        String AttendanceTime = entity.getAttendanceTime();
        if (AttendanceTime != null) {
            stmt.bindString(12, AttendanceTime);
        }
 
        Integer alive = entity.getAlive();
        if (alive != null) {
            stmt.bindLong(13, alive);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AttendanceScene readEntity(Cursor cursor, int offset) {
        AttendanceScene entity = new AttendanceScene( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cardID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // headphoto
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // headphotoRGB
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // headphotoBW
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // FaceUserId
            cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7), // feature
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ScenePhoto
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // SceneHeadPhoto
            cursor.getInt(offset + 10), // faceRecognition
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // AttendanceTime
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12) // alive
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AttendanceScene entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCardID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHeadphoto(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHeadphotoRGB(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHeadphotoBW(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFaceUserId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFeature(cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7));
        entity.setScenePhoto(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSceneHeadPhoto(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setFaceRecognition(cursor.getInt(offset + 10));
        entity.setAttendanceTime(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAlive(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AttendanceScene entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AttendanceScene entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AttendanceScene entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
